[wunderground]
update = true
updateurl = "http://rtupdate.wunderground.com/weatherstation/updateweatherstation.php"

[mqtt]
broker = "1.2.3.4:1883"
clientid = "wunderground-bridge"
username = "user"
password = "pass"
updatetopic = "wunderground-bridge/weather"